version: '2'
services:
   db:
     image: mysql:latest
     container_name: project_database
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: root
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: project_web
     ports:
       - "80:80"
     volumes:
       - ./plugin:/var/www/html/wp-content/plugins/plugin-name
       - ./theme:/var/www/html/wp-content/themes/theme-name
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: root
volumes:
    db_data: